### ISSUE TITLE
General discussion and tasks

### ISSUE THREAD

**Issue by XinGITLou** [HYF-Class21/agile-development-group4-loruki-rebuild#9]
# General issue section for Loruki Rebuild project
For questions and problems, leave a comment below this issue.

## Tasks distributions :planning

- [x] Project definition by Xin
- [x] Constraints by Neha
- [x] Communication plan by Marina
- [x] User-persona by Xin and Belkis
- [x] Backlog by Marina
- [x] Design by Neha
- [x] Development-strategy by Xin
- [x] Retrospective by Marina
## Tasks distributions : HTML and CSS

- [x] Title and nav links by Neha
- [x] Intro and demo by Marina
- [x] Credibility by Xin
- [x] Example-box by Marina
- [x] Cloud info by Xin
- [x] Supported language by Marina
